### ISSUE TITLE
Failed publication of more msgs 

### ISSUE THREAD

**Issue by dondiegodelabega** [iml130/firos#21]
Hello, I'm experiencing some issues while trying to publish on the OCB two messages: basically I noticed that a message ("RobotAgentProperties") had never been published on the OCB, even if the `rostopic echo` on the topic ("/robot_opil_v2/description_channel") printed properly the message. This message contains a UUID, as does another message ("ActualState") on another topic ("/robot_opil_v2/status_channel").

To isolate and investigate I killed my node and I manually published the messages through some tests.

### First test
After starting OCB, roscore and firos, I made this `rostopic pub`:

```
rostopic pub /robot_opil_v2/description_channel mars_agent_physical_robot_msgs/RobotAgentProperties "robot_id: {uuid: "[251,61,117,161,168,37,80,255,179,230,228,178,188,174,72,46]", description: ''}
type: {vehicle_type: 0}
footprint:
  header:
    seq: 0
    stamp: {secs: 0, nsecs: 0}
    frame_id: ''
  polygon:
    points:
    - {x: 0.0, y: 0.0, z: 0.0}
min_height: 0.0
max_height: 0.0
payload: 0.0
max_pos_x_vel: 0.0
max_neg_x_vel: 0.0
max_pos_x_acc: 0.0
max_neg_x_acc: 0.0
max_pos_y_vel: 0.0
max_neg_y_vel: 0.0
max_pos_y_acc: 0.0
max_neg_y_acc: 0.0
max_pos_ang_vel: 0.0
max_neg_ang_vel: 0.0
max_pos_ang_acc: 0.0
max_neg_ang_acc: 0.0
velocity_control_sensitivity: 0.0
min_turning_radius: 0.0
batt_capacity: 0.0
batt_max_voltage: 0.0
weight: 0.0
vendor: ''
action_capability:
- category: 0
  action: 0
  attributes:
  - {type: '', name: '', value: ''}
  description: ''" 
publishing and latching message. Press ctrl-C to terminate
```
Checked the entyty on the OCB through `GET localhost:1026/v2/entities/` and the related entity was published.

So, I runned another `rostopic pub` with a second message, as it follows:

```
rostopic pub /robot_opil_v2/status_channel mars_agent_physical_robot_msgs/ActualState "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
robot_id:
  uuid: "[251,61,117,161,168,37,80,255,179,230,228,178,188,174,72,46]"
  description: ''
MoveBaseSimpleState: 0" 
publishing and latching message. Press ctrl-C to terminate
```
Firos shell showed me this message:

```
[ERROR] [1562341387.645877]: bad callback: <function _publishToCBRoutine at 0x7f9a1e662848>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 748, in _invoke_callback
    cb(msg, cb_args)
  File "/home/walter/OPIL/mod.iot.ran/src/firos/firos/include/ros/topicHandler.py", line 158, in _publishToCBRoutine
    CloudPublisher.publishToCB(robot, topic, data, ROS_TOPIC_AS_DICT[topic])
  File "/home/walter/OPIL/mod.iot.ran/src/firos/firos/include/contextbroker/cbPublisher.py", line 99, in publishToCB
    completeJsonStr = ObjectFiwareConverter.obj2Fiware(self.posted_history[robotID], ind=0, dataTypeDict=definitionDict,  ignorePythonMetaData=True)
  File "/home/walter/OPIL/mod.iot.ran/src/firos/firos/include/FiwareObjectConverter/objectFiwareConverter.py", line 46, in obj2Fiware
    return clsself._json(en, ind)
  File "/home/walter/OPIL/mod.iot.ran/src/firos/firos/include/FiwareObjectConverter/objectFiwareConverter.py", line 68, in _json
    return json.dumps(obj.__dict__, default=clsself._complex_handler, indent=ind)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 0: invalid start byte
```
The entity has not been generated on the OCB and with the usual `GET localhost:1026/v2/entities/` there was only the "status_channel".

### Second test

Same as before, but I published first the "status_channel" message, then the "description_channel" one. Same error printed on the shell. This time the only entity on the OCB was the "status_channel" one.

### Third test

Removed the UUID from the "description_channel" message, then published through `rostopic pub` the "status_channel" message, then published the new "description_channel" one.

Same outputs of Second test.

### Fourth test

Firstly published the "description_channel" message (without the UUID), then the "status_channel" one (with the UUID). Everything correctly published. 

Maybe this behaviour has something to do with the UUID conversion, but I can't exclude this is somehow related to my workspace. On the ROS side, everything looks fine. I attach you the messages, the bag files and the GET responses of the first two tests.

Thank you for your time.

[Tests.zip](https://github.com/iml130/firos/files/3363531/Tests.zip)

**Comment by Luxxii** [comment]
Hi,

I cannot reproduce the errors from the first and second test. I tested them also via `rostopic pub` and needed to change the uuid (because `rostopic pub` strangely suggests using an string instead of an  array of bytes) to `[251,61,117,161,168,37,80,255,179,230,228,178,188,174,72,46]`

Did you notice, that you use `"` in your `rostopic pub` to set the uuid? Could this cause the error?


A call should look like follows: 
```test
rostopic pub /robot_opil_v2/status_channel mars_agent_physical_robot_msgs/ActualState "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
robot_id:
  uuid: [251,61,117,161,168,37,80,255,179,230,228,178,188,174,72,46]
  description: ''
MoveBaseSimpleState: 0" 
```

I did not tried your third or fourth test. But it seems that the uuid can only be converted once in firos independent of the Message.

Strangely i can either publish `ActualState` or `RobotAgentProperties` at first with no issues. But publishing the next Message  causes the error you mentioned above.


---
I also tracked this strange behaviour down and noticed a simple error of the implementation in `cbPublisher.py`. Here we are not sending all information we can retrieve to the conversion part of firos, which leads to this error.

The fix will be avialable later today. Thanks for mentioning the error!


I
