### ISSUE TITLE
Firos endpoint callback notification 

### ISSUE THREAD

**Issue by DLuensch** [iml130/firos#33]
Firos produces a notification for every message received from orion. This flutes the terminal:
![firos_enpoint_callback_notification](https://user-images.githubusercontent.com/6607057/67009686-7c4ed500-f0ec-11e9-9c04-b8368563c39a.png)

**Comment by Luxxii** [comment]
The `HTTP`-Server which is used in FIROS flutes the Terminal. It also only hapens in Python2 (not Python3).

I will look into it and try to remove duplicated Messages.
