### ISSUE TITLE
Automatic Refresh of firos web-browser with new data

### ISSUE THREAD

**Issue by Tahir-Rasheed-437** [iml130/firos#37]
I have a question regarding firos. Its not really an issue but just a question. I have recently started using firos. Have successful communications of my move-base topics with the cloud and the Web-Browser (http://localhost:1026/v2/entities) shows the content of the Orion-Conext Broker. However, it is not refreshed automatically. Even if the new data is coming, I have to refresh the web-browser manually to see the updates otherwise it will retain the previous values. Is there a way we can always keep the newest data on the web?

**Comment by ptrdtznr** [comment]
Indeed, its more a question than an issue. You could use an plugin in your browser which could refresh the website every t-seconds. Displayed entities are shown in pure JSON. You would need to run a HTTP endpoint/server in the browser to get notified about an update of an entity.
