### ISSUE TITLE
Do we have an implementation of FIROS on ROS2?

### ISSUE THREAD

**Issue by umerusman34** [iml130/firos#47]
I need to use FIROS with ROS2, is it possible?

**Comment by Luxxii** [comment]
Hi @umerusman34, I no longer work and maintain this project and saw that issues are still submitted here. 

FIROS was designed for ROS not ROS2, therefore it will probably not work. However the guys from @iml130 might know more!

**Comment by umerusman34** [comment]
@Luxxii is there any framework like FIROS for ROS2?

**Comment by ptrdtznr** [comment]
Hi, nope - we havent planned to migrate towards ROS2 with FIROS and we are not aware of any other solution.
