### ISSUE TITLE
can not launch firos from a launch file

### ISSUE THREAD

**Issue by marija185** [iml130/firos#6]
Hi Dominik,
we are facing some problems with launching firos from a common launch file. It works when starting from another terminal as:
```
rosrun firos core.py
```
But when putting this to a launch file: 
```
    <!-- Run FIROS -->
    <node name="firos" pkg="firos" type="core.py" />
```
it says error:
```
process[firos-5]: started with pid [29406]
usage: core.py [-h] [-P PORT] [--conf CONF_FOLD] [--ros-port ROS_PORT]
               [--ros-node-name ROS_NODE_NAME] [--loglevel LOGLEVEL]
core.py: error: unrecognized arguments: __name:=firos __log:=/home/marija/.ros/log/a4b8beac-3a8f-11e9-b1de-b0359ffc31f9/firos-5.log
[firos-5] process has died [pid 29406, exit code 2, cmd /home/marija/programi/FIWARE/gitlabOPIL/mod.sw.sp/src/firos/firos/core.py __name:=firos __log:=/home/marija/.ros/log/a4b8beac-3a8f-11e9-b1de-b0359ffc31f9/firos-5.log].
log file: /home/marija/.ros/log/a4b8beac-3a8f-11e9-b1de-b0359ffc31f9/firos-5*.log
```
Thanks,
Marija

**Comment by Luxxii** [comment]
The current FIROS does not allow additional arguments like `__name:=*` or `__log:=*`. 

I was not aware that a `roslaunch` sets additional arguments like this. I'll try to fix this as soon as possible.

**Comment by Luxxii** [comment]
The Error should be now removed via f9db90316200d95fb19d0dc7e04fe248deff09d1 
. This Issue is related with: #3 

You should be now able to start FIROS via `roslaunch`. It is also possible to add additional arguments, like the ros-port.

```xml
<launch>
    <node name="firos2" pkg="firos" type="core.py" args="--ros-port 4567" />
</launch>
```
Let me know if there are similar Issues!

Best Regards,
Dominik

**Comment by marija185** [comment]
Thanks Dominik, it works now!!!!
Best regards,
Marija

**Comment by marija185** [comment]
small remark - it also works without args:
```
    <node name="firos" pkg="firos" type="core.py" />
```
